[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer" 